### ISSUE TITLE
Warning in TestTraced.test_simple_network

### ISSUE THREAD

**Issue by SsnL** [SsnL/PyTorch-Reparam-Module#2]
```
test_simple_network (__main__.TestTraced) ... /afs/csail.mit.edu/u/t/tongzhou/miniconda3/lib/python3.7/site-packages/to
rch/nn/functional.py:1837: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect
. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means
 that the trace might not generalize to other inputs!
  if input.size(0) != target.size(0):
ok

----------------------------------------------------------------------
Ran 1 test in 4.442s

OK
```

Trace is 
```
torch.jit.TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't recor
d the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace
 might not generalize to other inputs!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test/test_reparam_module.py", line 70, in test_simple_network
    self._test(MyNet(), ((2, 10),))
  File "test/test_reparam_module.py", line 23, in _test
    reparam_m = torchreparam.ReparamModule(reparam_m, inp1 if self.traced else None)
  File "/afs/csail.mit.edu/u/t/tongzhou/PyTorch-Reparam-Module/torchreparam/reparam_module.py", line 87, in __init__
    traced_full_reparam_forward = torch.jit.trace(self._forward_with_param_and_buffers, example_input)
  File "/afs/csail.mit.edu/u/t/tongzhou/miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 656, in tr
ace
    var_lookup_fn, _force_outplace)
  File "/afs/csail.mit.edu/u/t/tongzhou/PyTorch-Reparam-Module/torchreparam/reparam_module.py", line 131, in _forward_
with_param_and_buffers
    return self.module(*inputs)
  File "/afs/csail.mit.edu/u/t/tongzhou/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489,
in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/afs/csail.mit.edu/u/t/tongzhou/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479,
in _slow_forward
    result = self.forward(*input, **kwargs)
  File "test/test_reparam_module.py", line 65, in forward
    return torch.nn.functional.cross_entropy(out, self.target.expand(out.size(0)))
  File "/afs/csail.mit.edu/u/t/tongzhou/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2021, in
cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/afs/csail.mit.edu/u/t/tongzhou/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1837, in
nll_loss
    if input.size(0) != target.size(0):
SystemError: <built-in method __bool__ of Tensor object at 0x7f1f084e31f8> returned a result with an error set
```

**Comment by SsnL** [comment]
fixed
